FROM python:3.9.4-alpine
LABEL maintainer="Romaric Yemeli"
WORKDIR /opt
# update image and install some prerequisites
RUN apk update && \
    apk add gcc musl-dev postgresql-dev && \
    apk add git bash
RUN pip install --upgrade pip    

# Cloning app     
# RUN git clone https://github.com/ulrichmonji/Projekt-1-kandidat.git /opt/
COPY ../Projekt-1-kandidat/ /opt/

# Install application requirements
RUN pip install -r requirements.txt

# Expose application PORT
EXPOSE 8080

# Run application
CMD ["python","manage.py","runserver","192.168.0.100:8080"]